//
//  Company.swift
//  HomeWork2
//
//  Created by Adel Khaziakhmetov on 15.07.2021.
//

//"Symbol": "IBM",
//"AssetType": "Common Stock",
//"Name": "International Business Machines Corporation",
//"Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
//"CIK": "51143",
//"Exchange": "NYSE",
//"Currency": "USD",
//"Country": "USA",
//"Sector": "TECHNOLOGY",
//"Industry": "COMPUTER & OFFICE EQUIPMENT",
//"MarketCapitalization": "124266709000",
//"EBITDA": "15822000000",
//"PERatio": "23.26",
//"DividendPerShare": "6.52",
//"DividendYield": "0.0465",
//"EPS": "5.98",
//"DividendDate": "2021-06-10",
//"ExDividendDate": "2021-05-07",


public struct Company: Codable {
    public var symbol: String
    public var assetType: String
    public var name: String
    public var description: String
    public var CIK: String
    public var exchange: String
    public var country: String
    public var sector: String
    public var industry: String
    public var marketCapitalization: String
    public var dividendDate: String
    public var exDividendDate: String
    public var dividendPerShare: Double?
    public var PERatio: Double?
    public var eps: Double?
    
    enum CodingKeys: String, CodingKey {
        case symbol = "Symbol"
        case assetType = "AssetType"
        case name = "Name"
        case description = "Description"
        case CIK = "CIK"
        case exchange = "Exchange"
        case country = "Country"
        case sector = "Sector"
        case industry = "Industry"
        case marketCapitalization = "MarketCapitalization"
        case dividendDate = "DividendDate"
        case exDividendDate = "ExDividendDate"
        case dividendPerShare = "DividendPerShare"
        case PERatio = "PERatio"
        case eps = "EPS"
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(symbol, forKey: .symbol)
        try container.encode(assetType, forKey: .assetType)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(CIK, forKey: .CIK)
        try container.encode(exchange, forKey: .exchange)
        try container.encode(country, forKey: .country)
        try container.encode(sector, forKey: .sector)
        try container.encode(industry, forKey: .industry)
        try container.encode(marketCapitalization, forKey: .marketCapitalization)
        try container.encode(dividendDate, forKey: .dividendDate)
        try container.encode(exDividendDate, forKey: .exDividendDate)
        try container.encode(dividendPerShare, forKey: .dividendPerShare)
        try container.encode(PERatio, forKey: .PERatio)
        try container.encode(eps, forKey: .eps)
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        symbol = try container.decode(String.self, forKey: .symbol)
        assetType = try container.decode(String.self, forKey: .assetType)
        name = try container.decode(String.self, forKey: .name)
        description = try container.decode(String.self, forKey: .description)
        CIK = try container.decode(String.self, forKey: .CIK)
        exchange = try container.decode(String.self, forKey: .exchange)
        country = try container.decode(String.self, forKey: .country)
        sector = try container.decode(String.self, forKey: .sector)
        industry = try container.decode(String.self, forKey: .industry)
        marketCapitalization = try container.decode(String.self, forKey: .marketCapitalization)
        dividendDate = try container.decode(String.self, forKey: .dividendDate)
        exDividendDate = try container.decode(String.self, forKey: .exDividendDate)
        
        let dividendPerShareString = try container.decode(String.self, forKey: .dividendPerShare)
        dividendPerShare = Double(dividendPerShareString)
        
        let PERatioString = try container.decode(String.self, forKey: .PERatio)
        PERatio = Double(PERatioString)
        
        let epsString = try container.decode(String.self, forKey: .eps)
        eps = Double(epsString)
    }
}

let mockCompanyString =
    """
{
    \"Symbol\": \"BABA\",
    \"AssetType\": \"Common Stock\",
    \"Name\": \"Alibaba Group Holding Limited\",
    \"Description\": \"Alibaba Group Holding Limited, also known as Alibaba Group and Alibaba.com, is a Chinese multinational technology company specializing in e-commerce, retail, Internet, and technology. Founded on 28 June 1999 in Hangzhou, Zhejiang, the company provides consumer-to-consumer (C2C), business-to-consumer (B2C), and business-to-business (B2B) sales services via web portals, as well as electronic payment services, shopping search engines and cloud computing services. It owns and operates a diverse portfolio of companies around the world in numerous business sectors.\",
    \"CIK\": \"1577552\",
    \"Exchange\": \"NYSE\",
    \"Currency\": \"USD\",
    \"Country\": \"USA\",
    \"Sector\": \"TRADE & SERVICES\",
    \"Industry\": \"SERVICES-BUSINESS SERVICES, NEC\",
    \"Address\": \"26/F TOWER ONE, TIMES SQUARE, 1 MATHESON STREET, CAUSEWAY BAY, HK\",
    \"FiscalYearEnd\": \"March\",
    \"LatestQuarter\": \"2021-03-31\",
    \"MarketCapitalization\": \"585581789000\",
    \"EBITDA\": \"128494002000\",
    \"PERatio\": \"25.41\",
    \"PEGRatio\": \"1.887\",
    \"BookValue\": \"345.61\",
    \"DividendPerShare\": \"None\",
    \"DividendYield\": \"0\",
    \"EPS\": \"8.45\",
    \"RevenuePerShareTTM\": \"265.43\",
    \"ProfitMargin\": \"0.21\",
    \"OperatingMarginTTM\": \"0.125\",
    \"ReturnOnAssetsTTM\": \"0.0373\",
    \"ReturnOnEquityTTM\": \"0.147\",
    \"RevenueTTM\": \"717289030000\",
    \"GrossProfitTTM\": \"296084000000\",
    \"DilutedEPSTTM\": \"8.45\",
    \"QuarterlyEarningsGrowthYOY\": \"0.476\",
    \"QuarterlyRevenueGrowthYOY\": \"0.639\",
    \"AnalystTargetPrice\": \"292.21\",
    \"TrailingPE\": \"25.41\",
    \"ForwardPE\": \"21.74\",
    \"PriceToSalesRatioTTM\": \"5.1\",
    \"PriceToBookRatio\": \"3.853\",
    \"EVToRevenue\": \"0.697\",
    \"EVToEBITDA\": \"2.739\",
    \"Beta\": \"0.804\",
    \"52WeekHigh\": \"319.32\",
    \"52WeekLow\": \"198.26\",
    \"50DayMovingAverage\": \"214.76\",
    \"200DayMovingAverage\": \"232.12\",
    \"SharesOutstanding\": \"2712500000\",
    \"SharesFloat\": \"1870838000\",
    \"SharesShort\": \"48269000\",
    \"SharesShortPriorMonth\": \"44519400\",
    \"ShortRatio\": \"3.83\",
    \"ShortPercentOutstanding\": \"0.02\",
    \"ShortPercentFloat\": \"0.0258\",
    \"PercentInsiders\": \"10.18\",
    \"PercentInstitutions\": \"35.8\",
    \"ForwardAnnualDividendRate\": \"0\",
    \"ForwardAnnualDividendYield\": \"0\",
    \"PayoutRatio\": \"0\",
    \"DividendDate\": \"None\",
    \"ExDividendDate\": \"None\",
    \"LastSplitFactor\": \"None\",
    \"LastSplitDate\": \"None\"
}
"""
