//
// RecipeList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StockList: Codable {
    public var data: [Stock]?
    public var status: String?

    public init(data: [Stock]? = nil, status: String? = nil) {
        self.data = data
        self.status = status
    }
}


let stockListTemp =
"""
{
    "pagination": {"limit":100,"offset":0,"count":100,"total":176457},

    "data":[
        {
            "name":"Microsoft Corporation",
            "symbol":"MSFT",
            "has_intraday":false,
            "has_eod":true,
            "country":null,
            "stock_exchange": {"name":"NASDAQ Stock Exchange","acronym":"NASDAQ","mic":"XNAS","country":"USA","country_code":"US","city":"New York","website":"www.nasdaq.com" }
        }
        ]
}
"""
